// Settings

export const tipoReserva = (tipoId) => {
    const types = ['No especificada', 'Entrada', 'Tour', 'Paquete'];
    return types[tipoId] ?? 'Invalida';
}

const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
export const today = new Date().toLocaleDateString(undefined, options);


// Cost and prices

export const prices = {
    adults: 100,
    kids: 50,
    season: 'baja'
}

export const amounts = {
    public: 0,
    agency: 0,
    sugested: 0,
}

export const profit = { max: 5, calculated: 0 };


// Parks and Tours

export const parks = ['xcaret basica', 'xcaret plus', 'xcaret de noche', 'xplor dia', 'xplor fuego', 'xoximilco', 'xelha','xenxes', 'xavage basico', 'xavage all inclusive'];

export const tours = ['TOUR XCARET BASICO', 'TOUR XCARET PLUS', 'TOUR XCARET BASICO DOS DIAS', 'TOUR XCARET PLUS DOS DIAS', 'TOUR XCARET DE NOCHE', 'TOUR XCARET XCLUSIVO DE NOCHE', 'TOUR XPLOR DIA','TOUR XPLOR FUEGO', 'TOUR XELHA', 'SHUTTLE XELHA', 'TOUR TULUM XELHA','TOUR COBA XELHA', 'TOUR XOXIMILCO', 'TOUR XIXEN CLASICO', 'TOUR XIXEN DE LUJO', 'TOUR XENOTES', 'TOUR XENSES', 'TOUR TULUM XENSES', 'TOUR TULUM COBA', 'TOUR XAVAGE BASICO', 'TOUR XAVAGE ALL INCLUSIVE', 'DOLPHINE RIDE'];

export const zones = {
    Cancun: [
        "PARADERO DEL RESIDENCE CANCUN",
        "NIZUC RESORT AND SPA",
        "THE WESTIN RESORT & SPA CANCUN ",
        "CLUB REGINA",
        "SUN PALACE",
        "OLEO CANCUN",
        "BEL AIR CANCUN",
        "BSEA CANCUN PLAZA",
        "ROYAL SOLARIS",
        "SUITES BRISAS",
        "SOLYMAR",
        "NOW EMERALD CANCÚN",
        "GR SOLARIS",
        "CROWN PARADISE CANCUN",
        "IBEROSTAR CANCUN",
        "SEADUST CANCUN",
        "ROYAL ISLANDER",
        "ROYAL CARIBBEAN",
        "EMPORIO FAMILY SUITES",
        "OMNI CANCUN",
        "GRAND OASIS  CANCUN FASE 3 (THE PYRAMID) ",
        "FIESTA AMERICANA CONDESA",
        "PARADISUS CANCUN ",
        "MARRIOTT RESORT CANCÚN",
        "J.W. MARRIOT",
        "HARD ROCK HOTEL CANCUN ",
        "SECRETS THE VINE CANCUN",
        "SANDOS CANCUN LIFESTYLE RESORT",
        "GOLDEN PARNASSUS RESORT & SPA",
        "RITZ CARLTON",
        "ROYAL SANDS",
        "OCCIDENTAL TUCANCUN",
        "LIVE AQUA CANCUN",
        "WESTIN LAGUNAMAR OCEAN",
        "PARK ROYAL BEACH CANCUN",
        "MELODY MAKER",
        "BEACH PALACE",
        "NYX  PICK UP EN PARADERO DE BUS BEACH PALACE",
        "CANOPY BY HILTON CANCUN LA ISLA",
        "FLAMINGO CANCUN ",
        "HYATT ZILARA ",
        "WYNDHAM ALLTRA CANCUN (ANTES PANAMA JACK)  ",
        "GRAND PARK ROYAL CANCUN CARIBE",
        "LE BLANC",
        "SUNSET ROYAL BEACH RESORT",
        "ROYALTON CHIC SUITES CANCUN ",
        "KRYSTAL CANCUN",
        "KRYSTAL GRAND CANCUN",
        "HYATT ZIVA",
        "FIESTA AMERICANA  CORAL BEACH PICKUP EN LA ARCADA",
        "BASE XCARET",
        "RIU CANCUN",
        "RIU PALACE LAS AMERICAS",
        "FIESTA AMERICANA VILLAS CANCUN",
        "SUNSET MARINA RESORT",
        "CORAL MAR",
        "DREAMS SANDS CANCUN ",
        "BEACHSCAPE KINHA PICK UP PARADERO BUS",
        "PRESIDENTE INTERCONTINENTAL PARADERO BUSES",
        "DOS PLAYAS",
        "RIU PENINSULA CANCUN",
        "RIU CARIBE",
        "REAL INN CANCUN BY CAMINO REAL",
        "CASA MAYA",
        "BREATHLESS CANCUN SOUL RESORT & SPA ",
        "THE ROYAL CANCUN",
        "OASIS PALM BEACH",
        "OCCIDENTAL COSTA CANCUN",
        "AQUAMARINA CANCUN",
        "OCEAN HOTEL & SPA",
        "TEMPTATION",
        "CANCUN BAY RESORT",
        "OCEAN VIEW CANCUN ARENAS",
        "IMPERIAL LAS PERLAS",
        "HOTEL RENAISSANCE CANCUN RESORT AND MARINA",
        "PLAZA MARINA PUERTO CANCUN",
        "DREAMS VISTA CANCUN",
        "MUELLE ULTRAMAR PTO JUAREZ",
        "ALL RITMO CANCUN RESORT & WATERPARK ",
        "GARZA BLANCA RESORT & SPA CANCUN ",
        "VILLAS DEL PALMAR",
        "BELOVED",
        "EXCELLENCE PYA MUJERES",
        "FINEST PLAYA MUJERES",
        "ATELIER LOBBY ESTUDIO",
        "ATELIER LOBBY ATELIER",
        "DREAMS PLAYA MUJERES",
        "SECRETS PLAYA MUJERES",
        "TRS CORAL",
        "PALLADIUM COSTA MUJERES",
        "MAJESTIC ELEGANCE COSTA MUJERES",
        "CATALONIA COSTA MUJERES",
        "PLANET HOLLYWOOD BEACH RESORT CANCUN",
        "RIU PALACE COSTA MUJERES",
        "RIU DUNAMAR",
        "ADHARA HACIENDA CANCUN",
        "HOSTEL AGUA Y FUEGO",
        "WYNDHAM GARDEN CANCUN",
        "OASIS SMART",
        "KRYSTAL URBAN CANCUN CENTRO",
        "FOUR POINTS BY SHERATON CANCUN",
        "MARRIOTT COURTYARD",
        "COMFORT INN CANCUN ",
        "MOON PALACE LOBBY GRAND",
        "MOON PALACE SUNRISE",
        "MOON PALACE NIZUC",
        "CITY EXPRESS PLUS CANCUN",
        "DREAMS NATURA RESORT AND SPA",
        "ROYALTON RIVIERA CANCÚN",
        "HAVEN RIVIERA CANCUN ",
        "HILTON CANCUN ",
        "ZOETRY PARAISO DE LA BONITA",
        "SENSIRA RESORT & SPA RIVIERA MAYA ",
        "MARGARITAVILLE ISLAND ",
        "DESIRE BAHIA PETEMPICH",
        "AZUL BEACH RIVIERA CANCUN",
        "BREATHLESS RIVIERA CANCUN",
        "HYATT ZIVA RIVIERA CANCUN ",
        "OCEAN CORAL & TURQUESA BY H10",
        "DREAMS SAPPHIRE RESORT & SPA ",
        "DREAMS RIVIERA CANCUN",
        "EXCELLENCE RIVIERA",
        "THE FIVES OCEAN FRONT",
        "HACIENDA MORELOS",
        "GRAND RESIDENCES PUERTO MORELOS",
        "DREAMS JADE",
        "EL CID",
        "HOTEL VENTUS PTO MORELOS"
        ],
    rivieraMaya: ["ALOFT TULUM","DREAMS TULUM","HOTEL PAVO REAL","BAHIA PRINC. SIAN KAAN","BAHIA PRINCIPE COBA","BAHIA PRINCIPE AKUMAL","BAHIA PRINCIPE TULUM","SUNSCAPE AKUMAL BEACH RESORTS","AKUMAL BAY","SECRETS AKUMAL","GRAND SIRENIS","PALLADIUM WHITESAND","PALLADIUM COLONIAL","HOTEL UNICO","DORADO SEASIDE","CATALONIA ROYAL TULUM","BARCELO RIVIERA","BARCELO CARIBE ","BARCELO COLONIAL","BARCELO PALACE","DREAMS PTO AVENTURAS","CATALONIA YUCATAN","CATALONIA RIVIERA","HARD ROCK RIVIERA LOBBY HEAVEN","HARD ROCK RIVIERA LOBBY HACIENDA","FLAMENCO XCARET","RIU LA LUPITA","SANDOS PLAYACAR PICKUP ESTACIONAMIENTO LOBBY","IBEROSTAR TUCAN","RIU YUCATAN","RIU PALACE MEXICO","VIVA MAYA","RIU PLAYACAR","ROYAL HIDEAWAY & SPA PLAYACAR","ALLEGRO PLAYACAR","VIVA AZTECA","RIU PALACE RIVIERA MAYA","REEF PLAYACAR","PLAYACAR CENTER","RIU TEQUILA","RESIDENCE INN BY MARRIOR PLAYA DEL CARMEN ","CITY EXPRESS PLAYA DEL CARMEN","WYNDHAM GARDEN PLAYA DEL CARMEN","PLAZA ANTIGUA 10 AV SUR POR 15 AV SUR","OLD NAVY (Antes Deportes Marti) ","PLAYACAR PALACE","GRAND HYATT PLAYA DEL CARMEN RESORT","THE REEF 28","PLAZA LAS PERLAS","WYNDHAM ALLTRA PDC ","HILTON PLAYA DEL CARMEN","BODEGUITA DEL 1/2 CALLE 34 Y 5TA AV","BODEGUITA DEL 1/2 CALLE 34 Y 5TA AV (XP & XS)","THE REEF COCO BEACH","PARADISUS PLAYA SUR","PARADISUS PLAYA NORTE","ROYAL HACIENDAS","SANDOS CARACOL","THE FIVES BEACH","OCEAN RIVIERA PARADISE","PRINCESS LOBBY YUCATAN","PRINCESS LOBBY RIVIERA","GRAND VELAS pick up lobby AMBASSADOR","BANYAN TREE MAYAKOBA","FAIRMONT MAYAKOBA","ROSEWOOD MAYAKOBA","ANDAZ MAYAKOBA","BLUE DIAMOND","BELMOND MAROMA RESORT & SPA","SECRETS CAPRI","OCEAN MAYA ROYALE BY H10","BLUE BAY GRAND ESMERALDA","HACIENDA TRES RIOS","DORADO MAROMA","SECRETS MAROMA","CATALONIA MAROMA","IBERO PARAISO MAYA","IBEROSTAR PARAISO LINDO","IBERO PARAISO BEACH","IBEROSTAR PARAISO DEL MAR","VIDANTA PUP EN LOBBY CENTRAL","VALENTIN IMPERIAL","NICKELODEON","GENERATIONS RIVIERA","DORADO ROYALE"],
    playaDelCarmen: ["ALOFT TULUM","DREAMS TULUM","HOTEL PAVO REAL","BAHIA PRINC. SIAN KAAN","BAHIA PRINCIPE COBA","BAHIA PRINCIPE AKUMAL","BAHIA PRINCIPE TULUM","SUNSCAPE AKUMAL BEACH RESORTS","AKUMAL BAY","SECRETS AKUMAL","GRAND SIRENIS","PALLADIUM WHITESAND","PALLADIUM COLONIAL","HOTEL UNICO","DORADO SEASIDE","CATALONIA ROYAL TULUM","BARCELO RIVIERA","BARCELO CARIBE ","BARCELO COLONIAL","BARCELO PALACE","DREAMS PTO AVENTURAS","CATALONIA YUCATAN","CATALONIA RIVIERA","HARD ROCK RIVIERA LOBBY HEAVEN","HARD ROCK RIVIERA LOBBY HACIENDA","FLAMENCO XCARET","RIU LA LUPITA","SANDOS PLAYACAR PICKUP ESTACIONAMIENTO LOBBY","IBEROSTAR TUCAN","RIU YUCATAN","RIU PALACE MEXICO","VIVA MAYA","RIU PLAYACAR","ROYAL HIDEAWAY & SPA PLAYACAR","ALLEGRO PLAYACAR","VIVA AZTECA","RIU PALACE RIVIERA MAYA","REEF PLAYACAR","PLAYACAR CENTER","RIU TEQUILA","RESIDENCE INN BY MARRIOR PLAYA DEL CARMEN ","CITY EXPRESS PLAYA DEL CARMEN","WYNDHAM GARDEN PLAYA DEL CARMEN","PLAZA ANTIGUA 10 AV SUR POR 15 AV SUR","OLD NAVY (Antes Deportes Marti) ","PLAYACAR PALACE","GRAND HYATT PLAYA DEL CARMEN RESORT","THE REEF 28","PLAZA LAS PERLAS","WYNDHAM ALLTRA PDC ","HILTON PLAYA DEL CARMEN","BODEGUITA DEL 1/2 CALLE 34 Y 5TA AV","BODEGUITA DEL 1/2 CALLE 34 Y 5TA AV (XP & XS)","THE REEF COCO BEACH","PARADISUS PLAYA SUR","PARADISUS PLAYA NORTE","ROYAL HACIENDAS","SANDOS CARACOL","THE FIVES BEACH","OCEAN RIVIERA PARADISE","PRINCESS LOBBY YUCATAN","PRINCESS LOBBY RIVIERA","GRAND VELAS pick up lobby AMBASSADOR","BANYAN TREE MAYAKOBA","FAIRMONT MAYAKOBA","ROSEWOOD MAYAKOBA","ANDAZ MAYAKOBA","BLUE DIAMOND","BELMOND MAROMA RESORT & SPA","SECRETS CAPRI","OCEAN MAYA ROYALE BY H10","BLUE BAY GRAND ESMERALDA","HACIENDA TRES RIOS","DORADO MAROMA","SECRETS MAROMA","CATALONIA MAROMA","IBERO PARAISO MAYA","IBEROSTAR PARAISO LINDO","IBERO PARAISO BEACH","IBEROSTAR PARAISO DEL MAR","VIDANTA PUP EN LOBBY CENTRAL","VALENTIN IMPERIAL","NICKELODEON","GENERATIONS RIVIERA","DORADO ROYALE"],
};

// Season

export const getSeason = (Date) => {
    const isHigh = ['2022-12-26','2022-12-27','2022-12-28', '2022-12-29', '2022-12-30', '2022-12-31'];
    return isHigh.includes(Date) ? 'high' : 'low';
}